# Generated by Django 4.1 on 2022-09-08 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participante',
            options={'permissions': (('agregar_participante', 'Agregar un usuario a un proyecto'), ('modificar_participante', 'Modificar un participante'), ('borrar_participante', 'Borrar participante'), ('listar_participante', 'Lista un participante individual'))},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': (('crear_proyecto', 'Crear un nuevo proyecto'), ('eliminar_proyecto', 'Eliminar un proyecto'), ('actualizar_proyecto', 'Actualizar los parametros iniciales de un proyecto'), ('archivar_proyecto', 'Archivar un proyecto'), ('cambiar_estado_proyecto', 'Modificar el estado de un proyecto'), ('listar_proyectos', 'Listar uno o varios proyectos'))},
        ),
        migrations.RenameField(
            model_name='participante',
            old_name='idProyecto',
            new_name='proyecto',
        ),
        migrations.RenameField(
            model_name='participante',
            old_name='idUsuario',
            new_name='usuario',
        ),
    ]
