# Generated by Django 4.1 on 2022-09-07 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={
                'permissions':
                    (('crear_proyecto', 'Crear un nuevo proyecto'),
                     ('eliminar_proyecto', 'Eliminar un proyecto'),
                     ('actualizar_proyecto', 'Actualizar los parametros iniciales de un proyecto'),
                     ('archivar_proyecto', 'Archivar un proyecto'),
                     ('cambiar_estado_proyecto', 'Modificar el estado de un proyecto'))},
        ),
    ]
