# Generated by Django 4.1 on 2022-09-08 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_alter_proyecto_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participante',
            old_name='idProyecto',
            new_name='proyecto',
        ),
        migrations.RenameField(
            model_name='participante',
            old_name='idUsuario',
            new_name='usuario',
        ),
    ]
