# Generated by Django 4.1 on 2022-09-09 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_alter_proyecto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participante',
            options={},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': (('crear_proyecto', 'Crear un nuevo proyecto'), ('eliminar_proyecto', 'Eliminar un proyecto'), ('actualizar_proyecto', 'Actualizar los parametros iniciales de un proyecto'), ('archivar_proyecto', 'Archivar un proyecto'), ('cambiar_estado_proyecto', 'Modificar el estado de un proyecto'), ('listar_proyectos', 'Listar uno o varios proyectos'), ('iniciar_proyecto', 'Marcar un proyecto como iniciado'), ('crear_tipo_HU', 'Crear un nuevo tipo de Historia de Usuario'), ('borrar_tipo_HU', 'Borrar un tipo de HU'), ('importar_roles_internos', 'Importar roles internos de otro proyecto'), ('agregar_participante', 'Agregar un usuario a un proyecto'), ('modificar_participante', 'Modificar un participante'), ('borrar_participante', 'Borrar participante'), ('listar_participante', 'Lista un participante individual'))},
        ),
    ]
