# Generated by Django 4.1 on 2022-09-21 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0009_alter_proyecto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': (('crear_proyecto', 'Crear un nuevo proyecto'), ('eliminar_proyecto', 'Eliminar un proyecto'), ('actualizar_proyecto', 'Actualizar los parametros iniciales de un proyecto'), ('archivar_proyecto', 'Archivar un proyecto'), ('cambiar_estado_proyecto', 'Modificar el estado de un proyecto'), ('listar_proyectos', 'Listar uno o varios proyectos'), ('iniciar_proyecto', 'Marcar un proyecto como iniciado'), ('crear_tipo_HU', 'Crear un nuevo tipo de Historia de Usuario'), ('borrar_tipo_HU', 'Borrar un tipo de HU'), ('importar_tipo_HU', 'Importar un tipo de HU'), ('importar_roles_internos', 'Importar roles internos de otro proyecto'), ('agregar_participante', 'Agregar un usuario a un proyecto'), ('modificar_participante', 'Modificar un participante'), ('borrar_participante', 'Borrar participante'), ('listar_participante', 'Lista un participante individual'), ('listar_roles_internos', 'Listar todos los roles internos del sistema'), ('crear_rol_interno', 'Crear un nuevo rol interno'), ('actualizar_rol_interno', 'Actualizar un rol interno'), ('borrar_rol_interno', 'Borrar un rol interno de proyecto'), ('modificar_columnas_tipo_HU', 'Añadir, eliminar o modificar columnas de un tipo de HU'))},
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='scrumMaster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
