# Generated by Django 4.1 on 2022-09-21 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0010_alter_proyecto_options_alter_proyecto_scrummaster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': (('crear_proyecto', 'Crear un nuevo proyecto'), ('eliminar_proyecto', 'Eliminar un proyecto'), ('actualizar_proyecto', 'Actualizar los parametros iniciales de un proyecto'), ('archivar_proyecto', 'Archivar un proyecto'), ('cambiar_estado_proyecto', 'Modificar el estado de un proyecto'), ('listar_proyectos', 'Listar uno o varios proyectos'), ('iniciar_proyecto', 'Marcar un proyecto como iniciado'), ('crear_tipo_HU', 'Crear un nuevo tipo de Historia de Usuario'), ('borrar_tipo_HU', 'Borrar un tipo de HU'), ('importar_tipo_HU', 'Importar un tipo de HU'), ('importar_roles_internos', 'Importar roles internos de otro proyecto'), ('agregar_participante', 'Agregar un usuario a un proyecto'), ('modificar_participante', 'Modificar un participante'), ('borrar_participante', 'Borrar participante'), ('listar_participante', 'Lista un participante individual'), ('listar_roles_internos', 'Listar todos los roles internos del sistema'), ('crear_rol_interno', 'Crear un nuevo rol interno'), ('actualizar_rol_interno', 'Actualizar un rol interno'), ('borrar_rol_interno', 'Borrar un rol interno de proyecto'), ('modificar_columnas_tipo_HU', 'Añadir, eliminar o modificar columnas de un tipo de HU'), ('actualizar_tipo_HU', 'Actualizar un tipo de Historia de Usuario'))},
        ),
    ]
