version: '3.8'

services:
  ubuntu:
    build: .
    command: /bin/sh -c "/etc/init.d/postgresql start;while sleep 1000; do :; done"
    volumes:
      - ./:/usr/src/app
      - vscode:/root/.vscode-server/extensions
      - vscode_insiders:/root/.vscode-server-insiders
    ports:
      - 8080:8080
      - 8081:8081
volumes:
  vscode:
  vscode_insiders: