# Generated by Django 4.1 on 2022-09-07 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': (('modificar_roles_externos_de_usuario', 'Permiso para el administrador de editar roles externos'),)},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
    ]
