# Generated by Django 4.1 on 2022-09-05 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_usuario_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': (('modificar_roles_externos_de_usuario', 'Permiso para el administrador de editar roles externos'),)},
        ),
    ]
