# Generated by Django 4.1 on 2022-09-05 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        ('roles', '0003_rol_delete_rolexterno'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.proyecto'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
