# Generated by Django 4.1 on 2022-09-06 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_rol_proyecto_alter_rol_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'default_permissions': (), 'permissions': (('listar_roles_internos', 'Listar todos los roles internos del sistema'), ('listar_roles_externos', 'Listar todos los roles externos del sistema'), ('crear_rol_interno', 'Crear un nuevo rol interno'), ('crear_rol_externo', 'Crear nuevo rol externo'), ('actualizar_rol_interno', 'Actualizar un rol interno'), ('actualizar_rol_externo', 'Actualizar un rol externo'), ('borrar_rol_interno', 'Borrar un rol interno de proyecto'), ('borrar_rol_externo', 'Borrar un rol externo del sistema'), ('listar_permisos_externos', 'Para listar los permisos de un rol externo'))},
        ),
    ]
