# Generated by Django 4.1 on 2022-09-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soportepermisos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soportepermisos',
            options={'default_permissions': (), 'managed': False, 'permissions': (('listar_roles', 'Listar todos los roles del sistema'), ('listar_roles_internos', 'Listar todos los roles internos del sistema'), ('listar_roles_externos', 'Listar todos los roles externos del sistema'))},
        ),
    ]
