# Generated by Django 4.1 on 2022-09-04 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soportepermisos', '0002_alter_soportepermisos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soportepermisos',
            options={'default_permissions': (), 'managed': False, 'permissions': (('listar_permisos', 'Listar/ver permisos del sistema'),)},
        ),
    ]
