# Generated by Django 4.1 on 2022-09-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Historia_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('fechaCreacion', models.DateTimeField()),
                ('proyect', models.ManyToManyField(to='proyectos.proyecto')),
            ],
        ),
    ]
