# Generated by Django 4.1 on 2022-09-08 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historiasDeUsuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo_historia_usuario',
            old_name='proyect',
            new_name='proyectos',
        ),
        migrations.CreateModel(
            name='Columna_Tipo_Historia_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('orden', models.IntegerField()),
                ('tipoHU', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='historiasDeUsuario.tipo_historia_usuario')),
            ],
        ),
    ]
